[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "email-validator>=2.2.0",
    "flask-login>=0.6.3",
    "flask>=3.1.0",
    "flask-sqlalchemy>=3.1.1",
    "gunicorn>=23.0.0",
    "networkx>=3.4.2",
    "numpy>=2.2.2",
    "psycopg2-binary>=2.9.10",
    "replit-object-storage>=1.0.2",
    "matplotlib>=3.10.1",
    "sqlalchemy>=2.0.37",
    "werkzeug>=3.1.3",
    "jinja2>=3.1.5",
]
