version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - apierrors
  - apiserver
  - Ayaka
  - cenkalti
  - chatcompletion
  - common_tasksv1
  - fatcontext
  - gorcon
  - grpcotel
  - grpcpkg
  - grpcservers
  - grpcservices
  - healthz
  - httppkg
  - inventoryapi
  - inventoryapiv1
  - labstack
  - maxbrunsfeld
  - Minimaxi
  - moeru
  - moeru-ai
  - Neko
  - nekomeowww
  - nolint
  - nonamedreturns
  - opentelemetry
  - Otel
  - otelgrpc
  - otelhttp
  - otlpmetric
  - otlpmetrichttp
  - otlptrace
  - otlptracehttp
  - protovalidate
  - robfig
  - samber
  - stdoutmetric
  - stdouttrace
  - taze
  - tsdown
  - Unmute
  - xsai
ignoreWords: []
import: []
