version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - apierrors
  - Apim
  - bmatcuk
  - browserbase
  - buildkit
  - bumpp
  - canonicalheader
  - chardata
  - cognitiveservices
  - containedctx
  - contextcheck
  - cyclop
  - dataurl
  - depguard
  - Describedby
  - Detailf
  - dockerclient
  - dockerfiles
  - doublestar
  - dupl
  - durationcheck
  - eastasia
  - elevenlabs
  - errcheck
  - errchkjson
  - errname
  - execinquery
  - exhaustive
  - exhaustruct
  - exportloopref
  - Facemotion
  - flac
  - flexstack
  - forbidigo
  - forcetypeassert
  - funlen
  - goarch
  - gochecknoglobals
  - gochecknoinits
  - gocognit
  - goconst
  - gocritic
  - gocyclo
  - godox
  - gofmt
  - gofumpt
  - goheader
  - goimports
  - gomnd
  - goprintffuncname
  - gosec
  - gosimple
  - govet
  - hreflang
  - importantimport
  - ineffassign
  - ireturn
  - jsonpatch
  - kbitrate
  - kbps
  - koemotion
  - labstack
  - lll
  - lmittmann
  - maintidx
  - misspell
  - moby
  - moeru
  - mulaw
  - musttag
  - nakedret
  - nekomeowww
  - nestif
  - nilnil
  - nlreturn
  - nolint
  - nolintlint
  - nosprintfhostport
  - opencontainers
  - paralleltest
  - perfsprint
  - pluginregistry
  - prealloc
  - predeclared
  - rawjson
  - reassign
  - repositoryurlrules
  - revive
  - Rinna
  - samber
  - slogecho
  - sonarjs
  - ssml
  - stagehead
  - staticcheck
  - strconv
  - tagalign
  - tenv
  - testableexamples
  - testpackage
  - Traceparent
  - truesilk
  - typecheck
  - unconvert
  - unparam
  - unspeech
  - unused
  - varnamelen
  - Vercel
  - whitespace
  - wrapcheck
  - wsl
ignoreWords: []
import: []
