version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - bumpp
  - contentlayer
  - daisyui
  - eslintcache
  - importantimport
  - Moeru
  - moeru-ai
  - nemo
  - njsproj
  - ntvs
  - pkgroll
  - sonarjs
  - valibot
  - vercel
  - vite
  - vitest
  - xsai
ignoreWords: []
import: []
