[workspace]
authors = [ "LemonNeko <selim@lemonneko.moe>" ]
channels = [ "conda-forge" ]
name = "airi-factorio"
platforms = [
  "osx-arm64",
  "win-64",
  "linux-64"
]
version = "0.1.0"
preview = [ "pixi-build" ]

[tasks]
lint = "ruff check ."
lint-fix = "ruff check . --fix"
typecheck = "ty check ."
train-yolo-v0 = { cmd = "python src/train.py", cwd = "./models/factorio-yolo-v0" }
predict-yolo-v0 = { cmd = "python src/predict.py", cwd = "./models/factorio-yolo-v0" }

[dependencies]
python = "<3.13"

[pypi-dependencies]
ruff = ">=0.13.3,<0.14"
ipython = ">=9.5.0, <10"
ipykernel = ">=6.30.1, <7"
ultralytics = ">=8.3.204,<9"
ty = ">=0.0.1a21, <0.0.1a22"

[package.build]
backend = { name = "pixi-build-python", version = "==0.3.2" }

[package.run-dependencies]
factorio-yolo-v0 = { path = "models/factorio-yolo-v0" }
