version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - AAAAIGZ
  - Airi
  - all-minilm
  - arktype
  - automd
  - BAAI
  - Bhdmlm
  - bumpp
  - Cerebras
  - changelogithub
  - codestral
  - cognitivecomputations
  - composio
  - dall
  - deepdml
  - deepinfra
  - deepseek
  - elevenlabs
  - eslintcache
  - fireworksai
  - fishaudio
  - flac
  - fumadocs
  - ggml
  - granularities
  - Groq
  - hexgrad
  - Hunyuan
  - importantimport
  - koemotion
  - Kokoro
  - litellm
  - llms
  - lmstudio
  - logprob
  - masknet
  - mastra
  - ministral
  - minzipped
  - mistralai
  - mixtral
  - modelcontextprotocol
  - moeru
  - moeru-ai
  - mxbai-embed-large
  - nemo
  - nemotron
  - netease
  - nomic
  - nomic-embed-text
  - Novita
  - nums
  - ollama
  - ONNX
  - openrouter
  - orama
  - pkgroll
  - Plateforme
  - qwen
  - reranker
  - rhasspy
  - scule
  - siliconflow
  - sonarjs
  - SoVITS
  - speaches
  - specdec
  - SSML
  - Stepfun
  - sury
  - Systran
  - theguild
  - togetherai
  - twoslash
  - typeschema
  - unrs
  - unspeech
  - valibot
  - vitest
  - voltagent
  - wizardlm
  - xsai
  - xsfetch
  - xsmcp
  - xsschema
  - youdao
  - Zhipu
ignoreWords: []
import: []
