version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - angvel
  - assetpack
  - automd
  - bumpp
  - bundlephobia
  - Caddyfile
  - charx
  - drei
  - Eldoria
  - foxact
  - generouted
  - gltf
  - hikari
  - importantimport
  - Janny
  - keyval
  - Kokoro
  - koota
  - lenml
  - linvel
  - lucide
  - masknet
  - metalness
  - mixamo
  - mixamorig
  - moeru
  - moeru-ai
  - msdf
  - Ollama
  - ONNX
  - onreading
  - orcust
  - packagephobia
  - PICO
  - pixiv
  - pkgroll
  - pmndrs
  - Risu
  - rolldown
  - Seraphina
  - sonarjs
  - Speaches
  - stdlib
  - subgoal
  - subgoals
  - thumbstick
  - travisvn
  - tris
  - tsup
  - uikit
  - verts
  - vite
  - viverse
  - vrma
  - vrmc
  - wlipsync
  - Xiaoyi
  - xsai
  - yuka
ignoreWords: []
import: []
