version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - airi
  - amhandler
  - amname
  - amtype
  - attacl
  - attalign
  - attbyval
  - attcacheoff
  - attcollation
  - attcompression
  - attfdwoptions
  - attgenerated
  - atthasdef
  - atthasmissing
  - attidentity
  - attinhcount
  - attisdropped
  - attislocal
  - attlen
  - attmissingval
  - attname
  - attndims
  - attnotnull
  - attnum
  - attoptions
  - attrelid
  - Attributify
  - attstattarget
  - attstorage
  - atttypid
  - atttypmod
  - Brugger
  - cientos
  - citext
  - crossws
  - Deditor
  - duckdb
  - earthdistance
  - Emscripten
  - enumlabel
  - enumtypid
  - etcdctl
  - eventa
  - guiiai
  - healthcheck
  - HNSW
  - hnswlib
  - huggingface
  - iconify
  - indcheckxmin
  - indclass
  - indcollation
  - indexdef
  - indexprs
  - indexrelid
  - indimmediate
  - indisclustered
  - indisexclusion
  - indislive
  - indisprimary
  - indisready
  - indisreplident
  - indisunique
  - indisvalid
  - indkey
  - indnatts
  - indnkeyatts
  - indnullsnotdistinct
  - indoption
  - indpred
  - indrelid
  - initdb
  - isready
  - kebabcase
  - knncolle
  - Logg
  - ltree
  - martinbeentjes
  - matchall
  - milvus
  - minioadmin
  - Moeru
  - mysqladmin
  - nndescent
  - nolyfill
  - nspacl
  - nspname
  - nspowner
  - ofetch
  - oid
  - oklch
  - PCA
  - pglite
  - pgvecto
  - pgvector
  - pinia
  - regclass
  - regnamespace
  - reka
  - relacl
  - relallvisible
  - relam
  - relchecks
  - relfilenode
  - relforcerowsecurity
  - relfrozenxid
  - relhasindex
  - relhasrules
  - relhassubclass
  - relhastriggers
  - relispartition
  - relispopulated
  - relisshared
  - relkind
  - relminmxid
  - relname
  - relnamespace
  - relnatts
  - reloftype
  - reloptions
  - relowner
  - relpages
  - relpartbound
  - relpersistence
  - relreplident
  - relrewrite
  - relrowsecurity
  - reltablespace
  - reltoastrelid
  - reltuples
  - reltype
  - shadcn
  - Splitpanes
  - sslmode
  - Supabase
  - tanstack
  - taze
  - tensorchord
  - tresjs
  - tsdown
  - TSNE
  - typacl
  - typalign
  - typanalyze
  - typarray
  - typbasetype
  - typbyval
  - typcategory
  - typcollation
  - typdefault
  - typdefaultbin
  - typdelim
  - typelem
  - typinput
  - typisdefined
  - typispreferred
  - typlen
  - typmodin
  - typmodout
  - typname
  - typnamespace
  - typndims
  - typnotnull
  - typoutput
  - typowner
  - typreceive
  - typrelid
  - typsend
  - typstorage
  - typsubscript
  - typtype
  - typtypmod
  - UMAP
  - umappp
  - unbird
  - unocss
  - unplugin
  - vueuse
  - xsai
ignoreWords: []
import: []
