name: Model Collection

# https://docs.github.com/en/actions/how-tos/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token
permissions:
  issues: write
  pull-requests: write
  contents: write

on:
  issues:
    types:
      - opened
      - edited
      - reopened

jobs:
  run-issues-fetcher:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          package_json_file: inventory/package.json
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24.x
          cache: "pnpm"

          cache-dependency-path: inventory/pnpm-lock.yaml
      - name: Install dependencies
        run: pnpm install
        working-directory: inventory

      - name: Run issues fetcher
        run: pnpm run fetch-issues
        working-directory: inventory
        env:
          ISSUE_ID: ${{ github.event.issue.number }}
          TRIGGER_ACTION: ${{ github.event.action }}
          GITHUB_TOKEN: ${{ github.token }}
          GITHUB_USERNAME: github-actions
